### ISSUE TITLE
Apparent Windows JLine issue

### ISSUE THREAD

**Issue by astei** [canyonmodded/canyon#14]
Reported on the Canyon Discord:
```
java.io.FileNotFoundException: C:\Users\****\AppData\Local\Temp\jline_git-Canyon-"fb1a8b7f".dll (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at jline.WindowsTerminal.loadLibrary(WindowsTerminal.java:293)
        at jline.WindowsTerminal.initializeTerminal(WindowsTerminal.java:240)
        at jline.Terminal.setupTerminal(Terminal.java:75)
        at jline.Terminal.getTerminal(Terminal.java:26)
        at jline.ConsoleReader.<init>(ConsoleReader.java:191)
        at jline.ConsoleReader.<init>(ConsoleReader.java:186)
        at jline.ConsoleReader.<init>(ConsoleReader.java:174)
        at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:132)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:649)
        at org.bukkit.craftbukkit.Main.main(Main.java:135)
```

**Comment by astei** [comment]
The culprit is https://github.com/jline/jline1/blob/master/src/main/java/jline/WindowsTerminal.java#L267.

There's not much we can do about it, except upgrade JLine on our end.
