### ISSUE TITLE
Crash of the minecraft client on the server.

### ISSUE THREAD

**Issue by bmlrX3k** [canyonmodded/canyon#27]
Hi, I haven't checked if this happens solo yet, but when I want to sleep in a multiplayer bed on the canyon server I installed, my minecraft client crashes automatically. Does anyone have the same problem?
Do you have a solution?
Sincerely.

**Comment by bmlrX3k** [comment]
java.lang.NullPointerException
	at gc.a(GuiChat.java:28)
	at net.minecraft.client.Minecraft.k(Minecraft.java:906)
	at net.minecraft.client.Minecraft.run(Minecraft.java:454)
	at java.lang.Thread.run(Unknown Source)

**Comment by bmlrX3k** [comment]
It's ok, the problem is solved because it came from a mod that had no connection with canyon, sorry for all those who tried to solve the problem.
