### ISSUE TITLE
Error when loading/generating world

### ISSUE THREAD

**Issue by he3als** [canyonmodded/canyon#44]
Hey, so I built Canyon with the instructions on the Github. I used the `canyon-server.jar` in the target folder. I ran the jar with the batch command (in a new folder); `java -Xmx12288M -Xms12288M -jar canyon-server.jar`

Here's my log:
```
C:\Users\boot9\Desktop\beta 1.7.3 - canyon>java -Xmx12288M -Xms12288M -jar canyon-server.jar
151 recipes
16 achievements
18:21:33 [INFO] Starting minecraft server version Beta 1.7.3
18:21:33 [INFO] Loading properties
18:21:33 [WARNING] **** SERVER IS RUNNING IN ONLINE MODE!
18:21:33 [WARNING] Clients who wish to connect to this server must be patched to use the correct session endpoint.
18:21:33 [INFO] This server is running Canyon version git-Canyon-6cd67f7 (MC: 1.7.3)
18:21:33 [INFO] Starting Minecraft server on *:25565
18:21:33 [INFO] Preparing level "world"
18:21:33 [SEVERE] java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
18:21:33 [SEVERE]       at net.minecraft.server.RegionFile.<init>(RegionFile.java:77)
18:21:33 [SEVERE]       at net.minecraft.server.RegionFileCache.a(RegionFileCache.java:40)
18:21:33 [SEVERE]       at net.minecraft.server.RegionFileCache.c(RegionFileCache.java:72)
18:21:33 [SEVERE]       at net.minecraft.server.ChunkRegionLoader.a(ChunkRegionLoader.java:18)
18:21:33 [SEVERE]       at net.minecraft.server.ChunkProviderServer.realLoadChunk(ChunkProviderServer.java:188)
18:21:33 [SEVERE]       at net.minecraft.server.ChunkProviderServer.requestChunkLoad(ChunkProviderServer.java:332)
18:21:33 [SEVERE]       at net.minecraft.server.ChunkProviderServer.getChunkAtAsync(ChunkProviderServer.java:94)
18:21:33 [SEVERE]       at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:157)
18:21:33 [SEVERE]       at net.minecraft.server.ChunkProviderServer.getOrCreateChunk(ChunkProviderServer.java:167)
18:21:33 [SEVERE]       at net.minecraft.server.World.getChunkAt(World.java:280)
18:21:33 [SEVERE]       at net.minecraft.server.World.getTypeId(World.java:227)
18:21:33 [SEVERE]       at net.minecraft.server.World.isEmpty(World.java:231)
18:21:33 [SEVERE]       at net.minecraft.server.World.a(World.java:198)
18:21:33 [SEVERE]       at net.minecraft.server.WorldProvider.canSpawn(WorldProvider.java:41)
18:21:33 [SEVERE]       at net.minecraft.server.World.canSpawn(World.java:98)
18:21:33 [SEVERE]       at net.minecraft.server.World.c(World.java:186)
18:21:33 [SEVERE]       at net.minecraft.server.World.<init>(World.java:148)
18:21:33 [SEVERE]       at net.minecraft.server.WorldServer.<init>(WorldServer.java:27)
18:21:33 [SEVERE]       at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:277)
18:21:33 [SEVERE]       at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:240)
18:21:33 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
18:21:33 [SEVERE]       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
18:21:33 [SEVERE]       at java.lang.Thread.run(Unknown Source)
18:21:33 [SEVERE] Unexpected exception
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at net.minecraft.server.RegionFile.<init>(RegionFile.java:77)
        at net.minecraft.server.RegionFileCache.a(RegionFileCache.java:40)
        at net.minecraft.server.RegionFileCache.c(RegionFileCache.java:72)
        at net.minecraft.server.ChunkRegionLoader.a(ChunkRegionLoader.java:18)
        at net.minecraft.server.ChunkProviderServer.realLoadChunk(ChunkProviderServer.java:188)
        at net.minecraft.server.ChunkProviderServer.requestChunkLoad(ChunkProviderServer.java:332)
        at net.minecraft.server.ChunkProviderServer.getChunkAtAsync(ChunkProviderServer.java:94)
        at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:157)
        at net.minecraft.server.ChunkProviderServer.getOrCreateChunk(ChunkProviderServer.java:167)
        at net.minecraft.server.World.getChunkAt(World.java:280)
        at net.minecraft.server.World.getTypeId(World.java:227)
        at net.minecraft.server.World.isEmpty(World.java:231)
        at net.minecraft.server.World.a(World.java:198)
        at net.minecraft.server.WorldProvider.canSpawn(WorldProvider.java:41)
        at net.minecraft.server.World.canSpawn(World.java:98)
        at net.minecraft.server.World.c(World.java:186)
        at net.minecraft.server.World.<init>(World.java:148)
        at net.minecraft.server.WorldServer.<init>(WorldServer.java:27)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:277)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:240)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
>
```

**Comment by astei** [comment]
This sounds like you built the server using JDK 9 or higher but then tried to run the server on Java 8.

The solution is to either use Java 11 (the latest LTS) or rebuild Canyon and ensure you are using Java 8 for the build.

**Comment by he3als** [comment]
How do I make sure it uses Java 11? I have it installed.

**Comment by astei** [comment]
Find out where you have Java 11 installed and run the server from there. Since you're on Windows, I'd look in `C:\Program Files\Java` or similar. Sorry, I barely use Windows these days, and I switched to macOS/Linux as my primary development environment a long time ago.

**Comment by he3als** [comment]
When I type in the command `mvn clean package` it says `bash: mvn: command not found`

**Comment by astei** [comment]
...you don't have Maven installed. Install it.

If you can't follow these steps, you should just use the latest CI build from https://ci.canyonmodded.com/job/canyon/

**Comment by he3als** [comment]
Oh yeah, I forgot about that. I tried it on a VM, so I forgot it didn't have Maven installed.
You should put that link on the Github page, so then it's easier for people.

**Comment by he3als** [comment]
Anyways, thank you!
