### ISSUE TITLE
Useless messages in the console

### ISSUE THREAD

**Issue by Blayung** [canyonmodded/canyon#63]
Basically, when anybody disconnects from the server, a java.net.SocketException stacktrace is printed in the console with the severe logger. You could maybe get rid of it in this fork?

```
20:17:56 [INFO] _Blay_ lost connection: disconnect.quitting
20:17:56 [SEVERE] java.net.SocketException: Socket closed
20:17:56 [SEVERE] 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
20:17:56 [SEVERE] 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
20:17:56 [SEVERE] 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
20:17:56 [SEVERE] 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
20:17:56 [SEVERE] 	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
20:17:56 [SEVERE] 	at net.minecraft.server.NetworkWriterThread.run(NetworkWriterThread.java:43)
```

**Comment by KoboDev** [comment]
This is simillar to #59 
And yes its utterly annoying.
